// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLn7OHHhJ4SCZNp5iCdxWcWoBU1QH-eK0',
    appId: '1:445691487322:web:3303388a12535caa14a463',
    messagingSenderId: '445691487322',
    projectId: 'drive-clone-e2e8f',
    authDomain: 'drive-clone-e2e8f.firebaseapp.com',
    databaseURL: 'https://drive-clone-e2e8f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drive-clone-e2e8f.appspot.com',
    measurementId: 'G-YZQPY4JHDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZWJu8jmwegfIFn9aqloTIhwN0mS6qo68',
    appId: '1:445691487322:android:39a88e803bbb72f314a463',
    messagingSenderId: '445691487322',
    projectId: 'drive-clone-e2e8f',
    databaseURL: 'https://drive-clone-e2e8f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drive-clone-e2e8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLOAhVqv2SVxHCF4e22o10hfluLKkCmig',
    appId: '1:445691487322:ios:f41fabc6cab036b714a463',
    messagingSenderId: '445691487322',
    projectId: 'drive-clone-e2e8f',
    databaseURL: 'https://drive-clone-e2e8f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drive-clone-e2e8f.appspot.com',
    iosBundleId: 'com.example.googleDriveCloneWithGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLOAhVqv2SVxHCF4e22o10hfluLKkCmig',
    appId: '1:445691487322:ios:68ee38488774397914a463',
    messagingSenderId: '445691487322',
    projectId: 'drive-clone-e2e8f',
    databaseURL: 'https://drive-clone-e2e8f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drive-clone-e2e8f.appspot.com',
    iosBundleId: 'com.example.googleDriveCloneWithGetx.RunnerTests',
  );
}
